package net.takaiwa.samples;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'takaiwa.net' at '15/08/29 18:11' with Gradle 2.4
 *
 * @author takaiwa.net, @date 15/08/29 18:11
 */
public class HelloWorldTest {

}
