package net.takaiwa.samples;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'takaiwa.net' at '15/08/29 18:11' with Gradle 2.4
 *
 * @author takaiwa.net, @date 15/08/29 18:11
 */
public class HelloWorld2 {
    public static void main(String[] args) {
        String msg = 0 < args.length ? args[0] : "";
        System.out.println("Hello, world2 args:" + msg);
    }
}
